### ISSUE TITLE
Gala 8.0.3 fails to build with Mutter 45.5

### ISSUE THREAD

**Issue by pimvullers** [elementary/gala#2119]
### What Happened?

Building gala on Gentoo with Mutter 45.5 failed with following error:
```
libmutter-13.vapi:1120.10-1120.14: error: The type name `pid_t' could not be found
 1120 | 		public pid_t get_pid ();
      | 		       ^~~~~            
../gala-8.0.3/lib/App.vala:161.23-161.28: error: The type name `pid_t' could not be found
  161 |     public GLib.SList<pid_t?> get_pids () {
      |                       ^~~~~~               
../gala-8.0.3/lib/App.vala:162.38-162.43: error: The type name `pid_t' could not be found
  162 |         var results = new GLib.SList<pid_t?> ();
      |                                      ^~~~~~     
Compilation failed: 3 error(s), 0 warning(s)
````

### Steps to Reproduce

Use Mutter 45.5, build gala

### Expected Behavior

Build passes

### OS Version

Other Linux

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by pimvullers** [comment]
Comparing to Gala-8.0.2 the previous type was `int` instead of `pid_t`. Reverting this part with below command fixes build:
```
sed -i -e "s#pid_t#int#" vapi/libmutter.vapi lib/App.vala src/WindowTracker.vala
```

**Comment by tintou** [comment]
I'm guessing it is because of your Vala version

**Comment by tintou** [comment]
You need 0.56.17 to have the pid_t type

**Comment by pimvullers** [comment]
Thanks, Gentoo is currently at 0.56.16 as stable. 0.56.17 is only available in unstable.
Might be good to have meson actually ensure proper vala version.

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/2482
