### PR TITLE
Initial support for mutter-7

### PR DESCRIPTION
**Pull request by tintou**
This adds the initial infrastructure support for libmutter-7, note that no work has been done to ensure that it builds with the very latest Mutter.

### CODE REVIEW

**Comment by decathorpe** [comment]
I could add this PR as p patch for the nightly builds on fedora, so we can see if the plumbing works as intended, and to see if any / which build issues pop up?

**Comment by tintou** [comment]
@decathorpe please do, that's done for you ;)

**Comment by decathorpe** [comment]
Alright, I've switched my CI builds to track the tintou/mutter-7 branch.

It looks like mutter 3.38 has removed some Clutter stuff again ...

```
[6/78] Compiling Vala source ../lib/ActivatableComponent.vala ../lib/Constants.vala ../lib/Plugin.vala ../lib/Utils.vala ../lib/WindowIcon.vala ../lib/WindowManager.vala
FAILED: lib/76b5a35@@gala@sha/ActivatableComponent.c lib/76b5a35@@gala@sha/Constants.c lib/76b5a35@@gala@sha/Plugin.c lib/76b5a35@@gala@sha/Utils.c lib/76b5a35@@gala@sha/WindowIcon.c lib/76b5a35@@gala@sha/WindowManager.c lib/gala.h lib/gala.vapi 
valac -C --target-glib=2.44 --hide-internal --enable-deprecated --vapidir=/builddir/build/BUILD/gala-3.3.2+git200619.125426.f37fd66b/vapi --define HAS_MUTTER330 --define HAS_MUTTER332 --define HAS_MUTTER334 --define HAS_MUTTER336 --define HAS_MUTTER338 /builddir/build/BUILD/gala-3.3.2+git200619.125426.f37fd66b/vapi/config.vapi --pkg gnome-desktop-3.0 --pkg granite --pkg mutter-clutter-7 --pkg mutter-cogl-pango-7 --pkg mutter-cogl-7 --pkg libmutter-7 --pkg libbamf3 --pkg plank --pkg gdk-x11-3.0 --pkg gtk+-3.0 --pkg gee-0.8 --pkg gmodule-2.0 --pkg gio-2.0 --pkg gobject-2.0 --target-glib ' 2.44.0' --pkg glib-2.0 --color=always --directory lib/76b5a35@@gala@sha --basedir ../lib --library gala --header lib/gala.h --vapi ../gala.vapi --gresources=/builddir/build/BUILD/gala-3.3.2+git200619.125426.f37fd66b/data/gala.gresource.xml ../lib/ActivatableComponent.vala ../lib/Constants.vala ../lib/Plugin.vala ../lib/Utils.vala ../lib/WindowIcon.vala ../lib/WindowManager.vala
mutter-clutter-7.vapi:4808.96-4808.109: error: The type name `Clutter.Vertex' could not be found
		public void get_allocation_vertices (Clutter.Actor? ancestor, [CCode (array_length = false)] Clutter.Vertex verts[4]);
		                                                                                             ^^^^^^^^^^^^^^
mutter-clutter-7.vapi:7035.91-7035.113: error: The type name `Clutter.AllocationFlags' could not be found
		public virtual void allocate (Clutter.Container container, Clutter.ActorBox allocation, Clutter.AllocationFlags flags);
		                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^
../lib/Plugin.vala:205.70-205.92: error: The type name `Clutter.AllocationFlags' could not be found
        private void actor_allocation_changed (Clutter.ActorBox box, Clutter.AllocationFlags f) {
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

Full build log: https://download.copr.fedorainfracloud.org/results/decathorpe/elementary-nightly/fedora-rawhide-x86_64/01489042-gala/build.log.gz

At least I can confirm that gala still compiles on fedora 32 / mutter 3.36 :)

**Comment by decathorpe** [comment]
These errors gone, now new errors (removed / renamed signals?)

```
[6/78] Compiling Vala source ../lib/ActivatableComponent.vala ../lib/Constants.vala ../lib/Plugin.vala ../lib/Utils.vala ../lib/WindowIcon.vala ../lib/WindowManager.vala
FAILED: lib/76b5a35@@gala@sha/ActivatableComponent.c lib/76b5a35@@gala@sha/Constants.c lib/76b5a35@@gala@sha/Plugin.c lib/76b5a35@@gala@sha/Utils.c lib/76b5a35@@gala@sha/WindowIcon.c lib/76b5a35@@gala@sha/WindowManager.c lib/gala.h lib/gala.vapi 
valac -C --target-glib=2.44 --hide-internal --enable-deprecated --vapidir=/builddir/build/BUILD/gala-3.3.2+git200620.084938.8c8e5d02/vapi --define HAS_MUTTER330 --define HAS_MUTTER332 --define HAS_MUTTER334 --define HAS_MUTTER336 --define HAS_MUTTER338 /builddir/build/BUILD/gala-3.3.2+git200620.084938.8c8e5d02/vapi/config.vapi --pkg gnome-desktop-3.0 --pkg granite --pkg mutter-clutter-7 --pkg mutter-cogl-pango-7 --pkg mutter-cogl-7 --pkg libmutter-7 --pkg libbamf3 --pkg plank --pkg gdk-x11-3.0 --pkg gtk+-3.0 --pkg gee-0.8 --pkg gmodule-2.0 --pkg gio-2.0 --pkg gobject-2.0 --target-glib ' 2.44.0' --pkg glib-2.0 --color=always --directory lib/76b5a35@@gala@sha --basedir ../lib --library gala --header lib/gala.h --vapi ../gala.vapi --gresources=/builddir/build/BUILD/gala-3.3.2+git200620.084938.8c8e5d02/data/gala.gresource.xml ../lib/ActivatableComponent.vala ../lib/Constants.vala ../lib/Plugin.vala ../lib/Utils.vala ../lib/WindowIcon.vala ../lib/WindowManager.vala
../lib/Plugin.vala:152.13-152.36: error: The name `allocation_changed' does not exist in the context of `Clutter.Actor' (mutter-clutter-7)
            actor.allocation_changed.connect (actor_allocation_changed);
            ^^^^^^^^^^^^^^^^^^^^^^^^
../lib/Plugin.vala:165.13-165.36: error: The name `allocation_changed' does not exist in the context of `Clutter.Actor' (mutter-clutter-7)
            actor.allocation_changed.disconnect (actor_allocation_changed);
            ^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

**Comment by decathorpe** [comment]
New errors! :tada:

```
../src/Background/Background.vala:186.33-186.36: warning: Argument 1: Cannot pass null to non-null parameter type
                        finish (null);
                                ^^^^
../src/Background/Background.vala:192.37-192.40: warning: Argument 1: Cannot pass null to non-null parameter type
                            finish (null);
                                    ^^^^
../src/Background/BackgroundManager.vala:128.9-128.28: warning: Gala.BackgroundManager.set_size hides inherited method `Clutter.Actor.set_size'. Use the `new' keyword if hiding was intentional
        public void set_size (float width, float height) {
        ^^^^^^^^^^^^^^^^^^^^
../src/ShadowEffect.vala:121.13-122.59: warning: unhandled error `GLib.Error'
../src/Widgets/WorkspaceClone.vala:62.28-62.36: error: The name `Path' does not exist in the context of `Cogl' (mutter-cogl-7)
            var path = new Cogl.Path ();
                           ^^^^^^^^^
../src/Widgets/WorkspaceClone.vala:64.13-64.50: error: The name `stroke_path' does not exist in the context of `Cogl.Framebuffer' (mutter-cogl-7)
            context.get_framebuffer ().stroke_path (pipeline, path);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/WorkspaceClone.vala:69.13-69.50: error: The name `stroke_path' does not exist in the context of `Cogl.Framebuffer' (mutter-cogl-7)
            context.get_framebuffer ().stroke_path (pipeline, path);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/IconGroup.vala:543.17-543.27: warning: `null' incompatible with return type `Clutter.Actor'
                return null;
                ^^^^^^^^^^^
../src/DBus.vala:89.17-89.68: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                (wm.background_group as BackgroundContainer).changed.connect (() => background_changed ());
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 3 error(s), 6 warning(s)
```

Build log: https://download.copr.fedorainfracloud.org/results/decathorpe/elementary-nightly/fedora-rawhide-x86_64/01495387-gala/build.log.gz

**Comment by decathorpe** [comment]
I'm hitting those errors, not sure how to work around them (looks like libmutter-7 removed some more APIs ...):

```
../src/ScreenshotManager.vala:265.13-265.28: error: The name `capture' does not exist in the context of `Clutter.Stage' (mutter-clutter-7)
            wm.stage.capture (false, {x, y, width, height}, out captures);
            ^^^^^^^^^^^^^^^^
```
I couldn't find an upstream change for a removal / change of `Clutter.Stage.capture`.

```
../src/Background/BackgroundSource.vala:123.17-123.34: error: The name `changed' does not exist in the context of `Gee.Map.Entry<int,Gala.Background>?' (gee-0.8)
                background.changed.disconnect (background_changed);
                ^^^^^^^^^^^^^^^^^^
../src/Background/BackgroundSource.vala:124.17-124.34: error: The name `destroy' does not exist in the context of `Gee.Map.Entry<int,Gala.Background>?' (gee-0.8)
                background.destroy ();
                ^^^^^^^^^^^^^^^^^^
```

This looks like an instance of Gee dictionary iteration issues (iteration over entries instead of values)?

```
../src/Background/BackgroundManager.vala:140.13-140.39: error: The name `background' does not exist in the context of `Meta.BackgroundActor' (libmutter-7)
            background_actor.background = background.background;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Background/BackgroundManager.vala:107.13-107.51: error: The name `vignette_sharpness' does not exist in the context of `Meta.BackgroundActor?' (libmutter-7)
            new_background_actor.vignette_sharpness = background_actor.vignette_sharpness;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Background/BackgroundManager.vala:108.13-108.43: error: The name `brightness' does not exist in the context of `Meta.BackgroundActor?' (libmutter-7)
            new_background_actor.brightness = background_actor.brightness;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Background/BackgroundManager.vala:111.30-111.60: error: The name `background' does not exist in the context of `Meta.BackgroundActor?' (libmutter-7)
            var background = new_background_actor.background.get_data<unowned Background> ("delegate");
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Background/SystemBackground.vala:67.13-67.39: error: The name `background' does not exist in the context of `Meta.BackgroundActor' (libmutter-7)
            background_actor.background = system_background;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Has `background` been removed from `Meta.BackgroundActor`? I didn't find an upstream change for this.

```
../src/Widgets/WindowClone.vala:355.21-355.52: error: 2 missing arguments for `void Clutter.Actor.allocate_preferred_size (float, float)'
                    child.allocate_preferred_size ();
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The `allocate_preferred_size` method takes two `float` arguments with mutter 3.38 but I have no idea which values to pass.

```
../src/Widgets/WorkspaceClone.vala:62.28-62.36: error: The name `Path' does not exist in the context of `Cogl' (mutter-cogl-7)
            var path = new Cogl.Path ();
                           ^^^^^^^^^
../src/Widgets/WorkspaceClone.vala:64.13-64.50: error: The name `stroke_path' does not exist in the context of `Cogl.Framebuffer' (mutter-cogl-7)
            context.get_framebuffer ().stroke_path (pipeline, path);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/WorkspaceClone.vala:69.13-69.50: error: The name `stroke_path' does not exist in the context of `Cogl.Framebuffer' (mutter-cogl-7)
            context.get_framebuffer ().stroke_path (pipeline, path);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

These errors are caused by upstream dropping `mutter-cogl-path` entirely:
https://gitlab.gnome.org/GNOME/mutter/-/commit/a5294ce55f138df1902c7c5ca6f6ecb224ffae92

```
../src/Background/BackgroundManager.vala:128.9-128.28: warning: Gala.BackgroundManager.set_size hides inherited method `Clutter.Actor.set_size'. Use the `new' keyword if hiding was intentional
        public void set_size (float width, float height) {
        ^^^^^^^^^^^^^^^^^^^^
../src/DBus.vala:67.17-67.68: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                (wm.background_group as BackgroundContainer).changed.connect (() => background_changed ());
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/ShadowEffect.vala:121.13-122.59: warning: unhandled error `GLib.Error'
../src/Widgets/WindowClone.vala:355.21-355.52: error: 2 missing arguments for `void Clutter.Actor.allocate_preferred_size (float, float)'
                    child.allocate_preferred_size ();
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/IconGroup.vala:543.17-543.27: warning: `null' incompatible with return type `Clutter.Actor'
                return null;
                ^^^^^^^^^^^
```

Those sound like valid warnings to me :)

**Comment by decathorpe** [comment]
I've now found the upstream causes for all compilation issues, and added links to the relevant mutter commits to the previous comment.

- `Clutter.Stage.capture()` was removed, use `clutter_stage_paint_to{buffer,framebuffer}` instead
- `Meta.BackgroundContent` getting split off of `Meta.BackgroundActor`
- `Clutter.Actor.allocate_preferred_size()` now takes (float width, float height) as arguments
- `Cogl.Path` was removed entirely

**Comment by decathorpe** [comment]
PS: I have surgically patched and/or removed all calls to changed/removed methods, and it makes gala compile *and* run without crashing. It does, however, not do anything after launch either.

It looks like the gala process gets stuck somewhere - it doesn't register with the session manager, and it doesn't draw anything. Looking at the mutter API calls I patched out (background drawing, screenshot support, workspace shadow effects etc.) I don't see a reason why those should have affected the "base" functionality of the compositor (drawing windows).

**Comment by davidmhewitt** [comment]
@decathorpe I've had a similar thing recently while looking into what would be needed for Gala to not crash when it runs against Wayland (still on mutter-6 here though). I ended up patching out some shadow effects and the window switcher due to various X11 dependencies, which got it to compile and run, but I was left with nothing but a black screen with a cursor and nothing else ever even attempted to start. So it seems like Gala didn't register with the session manager and was eventually killed.

I'll let you know if I find the cause because it may be similar.

**Comment by decathorpe** [comment]
@davidmhewitt yeah that sounds exactly the same. Black screen with only mouse cursor, no wingpanel, no plank, but nothing in the session logs except "gala didn't register with the session manager" ...

**Comment by decathorpe** [comment]
FYI, my current patches derived from this PR no longer build due to this commit:
https://github.com/elementary/gala/commit/c124a8552ddb57ce138e0b403322dbd90d404b47

PoniterLocator is no longer found with mutter 3.38 (obviously).

**Comment by davidmhewitt** [comment]
@decathorpe Here's a diff against this branch that gets Gala to build and run (though largely untested so far) on Fedora 33. I've not pushed it to this branch yet as it still needs some cleanup (and I still need to fix the PiP plugin).

https://gist.github.com/davidmhewitt/fdbb533222db6b5ea49271e30105803c

**Comment by decathorpe** [comment]
@davidmhewitt awesome, I'll try it out later today. I won't have power for a while and then I need to attend a lecture over zoom (though the two might overlap. fun times), but after that, I have some time :)

**Comment by decathorpe** [comment]
Update: I've been able to test the additional patch, and it makes gala compile *and* work on fedora 33, and I did not notice any issues while using it. I'll build an updated package for fedora soon, because having it work at all is better than it crashing :D

**Comment by davidmhewitt** [comment]
@decathorpe Great, I found an issue with the screenshots that I've fixed up since I first linked the gist and I've also cleaned up my patch a bit, so that's pushed to this branch now.

Still to do before this is ready to merge:

- [ ] Test the changes to the `WindowManager` constructor. These were necessary to get Gala to run against mutter-7, it otherwise just froze. I don't see any reason why we can't apply these changes to earlier versions too.
- [ ] Fix the PiP plugin, it relies on `Clutter.DragAction` which is gone, should hopefully be able to use the internal drag action with reletive ease.

**Comment by decathorpe** [comment]
The latest state of tintou/mutter-7 branch works fine as far as I can tell, so I've taken the latest state (commit 88e3294) and pushed it as an update to fedora 33+. The missing PiP plugin is very low priority for me right now. Thanks again :bow:

**Comment by davidmhewitt** [comment]
Just #968 to go and then we should be able to re-enable the PiP plugin in this branch and mark it ready for review.

**Comment by davidmhewitt** [comment]
Can confirm the PiP plugin compiles and works on Fedora 33. I've found an issue with the screenshot code that I'll try and resolve today.

**Comment by davidmhewitt** [comment]
Ok, good to go. I'm happy with your code @tintou if you're happy with mine :wink:

**Comment by tintou** [comment]
@davidmhewitt I'm totally happy with yours ;)

**Review by davidmhewitt — APPROVED** [review]
I'm approving the bits I didn't write :laughing:

**Comment by decathorpe** [comment]
Awesome, thanks to you both for your work on this! :tada:

**Comment by davidmhewitt** [comment]
No problem! It's beneficial to us to keep on top of the changes in mutter anyway. Means there's hopefully less work for elementary OS 7.0. Let us know if you notice another API break and we'll try and keep up!

**Comment by decathorpe** [comment]
>     * [x]  Test the changes to the `WindowManager` constructor against older mutter versions. These were necessary to get Gala to run against mutter-7, it otherwise just froze. I don't see any reason why we can't apply these changes to earlier versions too.

@davidmhewitt is it possible that this is also necessary in the lightdm greeter? It displays similar symptoms :/
