### ISSUE TITLE
Fails to build, implicit-function-declaration

### ISSUE THREAD

**Issue by xiota** [elementary/gala#2042]
### What Happened?

Introduced in be8b8a3a6003440647227c08ae96250d1ffb9134.  Current head affected (0c12d796ac9f11828d33a354dcb9597e4d45b8ef).
```
src/gala.p/WindowManager.c:2610:9: error: implicit declaration of function ‘atk_bridge_adaptor_init’ [-Wimplicit-function-declaration]
 2610 |         atk_bridge_adaptor_init (0, _tmp1_, (gint) 0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
```

Compiler info:
```
C compiler for the host machine: cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240805")
C linker for the host machine: cc ld.bfd 2.43.0
Vala compiler for the host machine: valac (valac 0.56.17)
```

### Steps to Reproduce

Clone repo.  Configure and build with meson.  See error.

### Expected Behavior

Should build without error.  Commit 70e4642f8911cdee4cde941f6ec817971e947aa3 built successfully.

### OS Version

Other Linux

### Software Version

Compiled from git
