### PR TITLE
Fix fullscreen a maximized chromium window on secondary screen

### PR DESCRIPTION
**Pull request by andreasfelix**
~~Temporary~~ Fix for #404.

### CODE REVIEW

**Comment by andreasfelix** [comment]
I used this branch from some time now and didn't notice any side effects or other glitches. So I think it could be used as temporary fix till someone with more experience provides a better/cleaner solution...

**Comment by andreasfelix** [comment]
I have added a commit according to your suggestion, where signals are not connected when operation is fullscreen/unfullscreen.

But I think the lines
```vala
ulong size_signal_id = 0U;
ulong position_signal_id = 0U;
```
are needed in both cases. Otherwise I get a compilation error:
```
../src/WindowManager.vala:973.66-973.83: error: The name `position_signal_id' does not exist in the context of `Gala.WindowManagerGala.size_change'
				window_change_complete (actor, which_change, size_signal_id, position_signal_id);
```
So i put these lines in front of the if-else statement.

**Comment by andreasfelix** [comment]
After spending some time reading the source code and older PRs, I think I figured out a proper fix:

**Overview of the problem:**
The issue was introduced with #239, which was needed to fix the window animations. These weren't working as expected, because of an internal change of mutter, which caused the `Meta.Window.get_frame_rect` to update after the `Meta.Plugin.size_change` call. This led to the problem that the window transitions were using the old window size instead of the new window size. So it looked as no animation would happen.

The idea of #239 to fix this was to use the `size_changed` signal of the `Meta.Window`, so that in a later callback `get_frame_rect` would return the new window size. While this worked as expected for *(un)-maximizing* or *tiling* a window, it has a "small logical error": 

`Meta.Plugin.size_changed` also handles events where the size of the window must not change in general. For these events `Meta.Plugin.size_changed_completed` is not called, which practically disables these actions. This cases are:

#341: Moving a tilled window, which does not change its size. This was already solved (#387) by also registering `window_change_complete` to the `Meta.Window.position_changed` changed signal.

#404: Fullscreening an already maximized window, which also does not change its size. The reason this issue does **not** occur on a primary screen is because of the *wingpanel*. After fullscreening a maximized window on a primary screen the window actually increases its size by the area of the wingpanel, so that the `Meta.Window.size_changed` signal gets emitted anyway. This is not the case for a secondary display, which does not have a wingpanel! 

To reproduce this issue on a primary screen just `killall cerbere` and the `killall wingpanel`.

**One Solution (this PR)**
(Un-)Fullscreen does not need to know the s the rectangle that bounds window, so there is no need to connect these cases to the `size/position-changed` events (which are only used to await this property).

**New proposed logic:**

```
// pseudo code
size_change
    If (FULLSCREEN or UNFULLSCREEN)
       handle_fullscreen_window()
    else if (no matching tilled window)
      connect to positon/size_changed --> size_change_complete gets called by callback
      return;
    size_change_complete()
```

**Questions**
I am not completely sure, if there could be other edge cases, as I can't find the `Meta.Plugin.size_change_completed` in the [MutterAPI reference 3.16.1.1](https://developer.gnome.org/meta/stable). Isn't there a newer one? 

Where can I find a list of all possible values for `Meta.SizeChange`? If there are only `FULLSCREEN`, `UNFULLSCREEN`, `MAXIMIZE` and `UNMAXIMIZE`, I think this branch covers all cases.

It would be nice to get some feedback from @donadigo, @danrabbit, @peteruithoven and @ricotz as you already fixed the related issues #239 and #387.

**Other solution:**
Another possibility would be to implement a similar method to `Meta.Window.get_frame_rect` for the new window size in Mutter, so the callback work-around would not be needed. This would also prevent future edge cases.

**Comment by peteruithoven** [comment]
@andreasfelix thanks for looking into this so thoroughly.  
I wanted to reproduce #404 so I killed the Wingpanel (I recommend [this method](https://elementary.io/docs/code/os-dev#wingpanel)) and maximized and then fullscreen Terminal. It seems to work fine though? Also with other apps. 
Screen record from 2019-07-11 16 18 26

Am I doing something different?

**Comment by andreasfelix** [comment]
@peteruithoven try to log the `size_change_completed` call. You will see that the callback it is not called for maximized windows when fullscreening, instead the callbacks stack up until the next `position/size-changed` signal is emitted.

Some applications can cope with that (like terminal). For some applications the glitch only occurs sometimes (for me code, files, firefox) In some applications there are only minor glitches (epiphany). 

For me it always happens with a Chromium window with disabled system titlebar and borders.

**Comment by andreasfelix** [comment]
@peteruithoven, Also the applications will always correctly maximizes, but will not be usable. Try to type something in the terminal or scroll through some folders in files.

Sometimes this also happens for the terminal for me.

**Comment by donadigo** [comment]
@andreasfelix thank you for such detailed investigation. For all values of `SizeChange` please refer to the vapi: https://github.com/elementary/gala/blob/master/vapi/libmutter.vapi#L1393, these 4 are indeed all the values there are. Unfortunately I don't have access to a multi monitor setup, so I can't test this, but I will revise the logic again when reviewing.

**Comment by andreasfelix** [comment]
@donadigo to test this on a single monitor kill the wingpanel.

**Comment by andreasfelix** [comment]
To show that I am not the only one who experiences this issue, I listed the others reports. 
- https://www.reddit.com/r/elementaryos/comments/a5jme6/fullscreen_video_freezes_on_external_monitor/
- https://www.reddit.com/r/elementaryos/comments/bugb2v/having_a_problem_with_gala_and_fullscreening/
- https://www.reddit.com/r/elementaryos/comments/aoxof2/the_most_annoying_bug_on_elementary_os_judo_50/

- https://elementaryos.stackexchange.com/questions/16526/unable-to-fullscreen-video-on-second-monitor
- https://elementaryos.stackexchange.com/questions/16595/going-fullscreen-with-a-browser-locks-up-that-window-only-on-secondary-display
- https://www.reddit.com/r/elementaryos/comments/9y62ca/cant_fullscreen_a_video_on_secondary_monitor/
- https://elementaryos.stackexchange.com/questions/17082/instability-in-full-screen-videos-elementaryos-5
- https://elementaryos.stackexchange.com/questions/15561/google-chrome-stuck-when-watching-video-at-full-screen-size

The corresponding issue #404 is also the most commented gala-issue within the last year. I don't want to push anyone, but I would appreciate it, if somebody could review this branch, so this bug gets finally fixed. Thank you!
