### ISSUE TITLE
fails to compile with mutter 49.0 final

### ISSUE THREAD

**Issue by decathorpe** [elementary/gala#2556]
It looks like the support for mutter 49 that was added in #2525 was incomplete - there seem to have been breaking API changes between 49.alpha and 49.0 final. gala now fails to compile with these issues on Fedora 43+ with GNOME 49.0:

```
../lib/DragDropAction.vala: In function ‘gala_drag_drop_action_real_handle_event’:
../lib/DragDropAction.vala:204:13: error: implicit declaration of function ‘clutter_event_get_device’; did you mean ‘clutter_event_get_source’? [-Wimplicit-function-declaration]
  204 |                     grab_actor (actor, event.get_device ());
      |             ^       ~~~~~~~~~~~~~~~~
      |             clutter_event_get_source
../lib/DragDropAction.vala:204:11: error: assignment to ‘ClutterInputDevice *’ {aka ‘struct _ClutterInputDevice *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  204 |                     grab_actor (actor, event.get_device ());
      |           ^
../lib/DragDropAction.vala: In function ‘gala_drag_drop_action_on_event’:
../lib/DragDropAction.vala:250:9: error: assignment to ‘ClutterInputDevice *’ {aka ‘struct _ClutterInputDevice *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  250 |             var device = event.get_device ();
      |         ^
../lib/DragDropAction.vala:329:14: error: assignment to ‘ClutterInputDevice *’ {aka ‘struct _ClutterInputDevice *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  329 |                             grab_actor (handle, event.get_device ());
      |              ^

```

There is also a different error that gets printed during the build, but I'm not sure whether that's fatal or not:

```
[214/344] /usr/bin/meson --internal msgfmthelper --msgfmt=/usr/bin/msgfmt ../data/gala.metainfo.xml.in data/gala.metainfo.xml xml /builddir/build/BUILD/gala-8.2.5_20250816.git3442a1a-build/gala-3442a1ab57058957e6c07ada9b1d06a8bbc629cd/po
/usr/bin/msgfmt: libxml2 error: unterminated entity reference  ドロップの形をした適切なポインターを使用するように修正
```

**Comment by LuminousHustler** [comment]
https://github.com/elementary/gala/pull/2720 was merged. Closing

**Comment by decathorpe** [comment]
Thanks, can confirm that this builds correctly on Fedora 43+ (have not tested actually running it though).
