### PR TITLE
Fix building with gcc 14

### LINKED ISSUE #2042: Fails to build, implicit-function-declaration
### What Happened?

Introduced in be8b8a3a6003440647227c08ae96250d1ffb9134.  Current head affected (0c12d796ac9f11828d33a354dcb9597e4d45b8ef).
```
src/gala.p/WindowManager.c:2610:9: error: implicit declaration of function ‘atk_bridge_adaptor_init’ [-Wimplicit-function-declaration]
 2610 |         atk_bridge_adaptor_init (0, _tmp1_, (gint) 0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
```

Compiler info:
```
C compiler for the host machine: cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240805")
C linker for the host machine: cc ld.bfd 2.43.0
Vala compiler for the host machine: valac (valac 0.56.17)
```

### Steps to Reproduce

Clone repo.  Configure and build with meson.  See error.

### Expected Behavior

Should build without error.  Commit 70e4642f8911cdee4cde941f6ec817971e947aa3 built successfully.

### OS Version

Other Linux

### Software Version

Compiled from git

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by ryonakano**
Fixes #2042

Confirmed build success on:

- elementary OS 8 Early Access (gcc 13.2.0)
- Fedora 40 Workstation (gcc 14.2.1)

Confirmed Gala runs as expected on:

- elementary OS 8 Early Access

### CODE REVIEW

**Review by meisenzahl — APPROVED** [review]
I can confirm that this fixes the build errors on Fedora 40.

Before: https://github.com/meisenzahl/distro-agnostic/actions/runs/10476492737/job/29195187989?pr=23

After: https://github.com/meisenzahl/distro-agnostic/actions/runs/10535811298/job/29195257546?pr=23
